name: Compile and Update typst

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Typst
        uses: typst-community/setup-typst@v4

      - name: Verify Typst installation
        run: typst --version

      - name: Run Typst build script
        run: |
          chmod +x scripts/updateTypstFiles.sh
          ./scripts/updateTypstFiles.sh

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: typst-pdf-output
          path: output/**/*.pdf
      - name: Commit and push PDFs
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add output/**/*.pdf
            git commit -m "Auto-generate PDFs from Typst [skip ci]" || exit 0
            git push
